language: java

services:
  - docker

before_install:
  - docker-compose up -d && sleep 10

script: >
  docker ps;
  testResults="echo $(curl -i /tests/basic/_index.cfm?opt_run=true&reporter=json&target=tests.basic.basic)";
  echo "$testResults";
  if ! grep -i "http/1.1 200" <<< $testResults; then exit 1; fi